### ISSUE TITLE
Runtime error under alpine linux

### ISSUE THREAD

**Issue by NikolayFrantsev** [editorconfig-checker/editorconfig-checker#312]
Hey, I'm trying to run `editorconfig-checker.javascript` in my CI under alpine docker image.

Simplified `Dockerfile` example:

```dockerfile
FROM node:16-alpine

RUN yarn add editorconfig-checker
RUN node_modules/.bin/editorconfig-checker
```

Docker run command:

```
docker build -t editorconfig-issue .
```

Unfortunatelly process fails with following error message:

```
editorconfig-checker/editorconfig-checker.javascript#6 2.474 panic: runtime error: invalid memory address or nil pointer dereference
editorconfig-checker/editorconfig-checker.javascript#6 2.474 [signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x698912]
editorconfig-checker/editorconfig-checker.javascript#6 2.474 
editorconfig-checker/editorconfig-checker.javascript#6 2.474 goroutine 1 [running]:
editorconfig-checker/editorconfig-checker.javascript#6 2.474 github.com/editorconfig-checker/editorconfig-checker/pkg/files.GetFiles.func2(0xc000411270, 0xd, 0x0, 0x0, 0x7a9700, 0xc000075b60, 0x0, 0x0)
editorconfig-checker/editorconfig-checker.javascript#6 2.474 	/home/maex/projects/own/editorconfig-checker/editorconfig-checker/pkg/files/files.go:103 +0x52
editorconfig-checker/editorconfig-checker.javascript#6 2.474 path/filepath.walk(0xc0004111e0, 0xb, 0x7af8e0, 0xc00007fd40, 0xc0000d9c90, 0x0, 0x0)
editorconfig-checker/editorconfig-checker.javascript#6 2.474 	/home/maex/.asdf/installs/golang/1.13.3/go/src/path/filepath/path.go:378 +0x20c
editorconfig-checker/editorconfig-checker.javascript#6 2.474 path/filepath.walk(0xc000458ae8, 0x8, 0x7af8e0, 0xc000301d40, 0xc0000d9c90, 0x0, 
editorconfig-checker/editorconfig-checker.javascript#6 2.474 0x0)
editorconfig-checker/editorconfig-checker.javascript#6 2.474 	/home/maex/.asdf/installs/golang/1.13.3/go/src/path/filepath/path.go:382 +0x2ff
editorconfig-checker/editorconfig-checker.javascript#6 2.474 path/filepath.walk(0xc000370a30, 0x5, 0x7af8e0, 0xc000375ee0, 0xc0000d9c90, 0x0, 0x0)
editorconfig-checker/editorconfig-checker.javascript#6 2.474 	/home/maex/.asdf/installs/golang/1.13.3/go/src/path/filepath/path.go:382 +0x2ff
editorconfig-checker/editorconfig-checker.javascript#6 2.474 path/filepath.walk(0xc00001600b, 0x1, 0x7af8e0, 0xc00007fc70, 0xc0000d9c90, 0x0, 0x0)
editorconfig-checker/editorconfig-checker.javascript#6 2.474 	/home/maex/.asdf/installs/golang/1.13.3/go/src/path/filepath/path.go:382 +0x2ff
editorconfig-checker/editorconfig-checker.javascript#6 2.474 path/filepath.Walk(0xc00001600b, 0x1, 0xc000061c90, 0x0, 0x7a9740)
editorconfig-checker/editorconfig-checker.javascript#6 2.474 	/home/maex/.asdf/installs/golang/1.13.3/go/src/path/filepath/path.go:404 +0xff
editorconfig-checker/editorconfig-checker.javascript#6 2.474 github.com/editorconfig-checker/editorconfig-checker/pkg/files.GetFiles(0x0, 0x7405e9, 0x5, 0x0, 0x0, 0x0, 0x9bb348, 0x0, 0x0, 0x9930a0, ...)
editorconfig-checker/editorconfig-checker.javascript#6 2.474 	/home/maex/projects/own/editorconfig-checker/editorconfig-checker/pkg/files/files.go:102 +0x55a
editorconfig-checker/editorconfig-checker.javascript#6 2.474 main.main()
editorconfig-checker/editorconfig-checker.javascript#6 2.474 	/home/maex/projects/own/editorconfig-checker/editorconfig-checker/cmd/editorconfig-checker/main.go:107 +0x2e7
editorconfig-checker/editorconfig-checker.javascript#6 2.474 
```

Any ideas to deal with that?

**Comment by klaernie** [comment]
I cannot reproduce it with release v3.1.2 - hence I'll close the issue.
